### ISSUE TITLE
Enable Compression in httpd config

### ISSUE THREAD

**Issue by ericenns** [phac-nml/puppet-irida#40]
Adding
```
SetOutputFilter DEFLATE
```
to the `VirtualHost` config makes httpd compress responses when `Accept-Encoding: gzip, deflate` is present in the request header which chrome and other browsers add by default.

This change will result in faster page loads and a reduction in network load as gzipped responses will be returned to the client.

**Comment by Takadonet** [comment]
Changes in Production branch
